secrets:
  shared:
    NEWSER_GENERAL_JWT_SECRET: change-me
    NEWSER_SERVER_JWT_SECRET: change-me
    JWT_SECRET: change-me
    NEWSER_CAPABILITY_SIGNING_SECRET: capability-secret-change-me
    OPENAI_API_KEY: sk-your-key
  api:
    NEWSER_SERVER_PLAN_DRY_RUN_ENABLED: "true"
    NEWSER_SERVER_RUN_MANIFEST_ENABLED: "true"
    NEWSER_SERVER_RUN_STREAM_ENABLED: "true"
  worker:
    NEWSER_STORAGE_REDIS_PASSWORD: ""
    NEWSER_STORAGE_POSTGRES_PASSWORD: change-me
  executor:
    NEWSER_SECURITY_DEFAULT_TIMEOUT: 120s
  crawler:
    NEWSER_SOURCES_WEB_SEARCH_BRAVE_API_KEY: your-brave-key
    NEWSER_SOURCES_WEB_SEARCH_SERPER_API_KEY: your-serper-key
  memory:
    NEWSER_MEMORY_SEMANTIC_ENABLED: "false"
    NEWSER_MEMORY_SEMANTIC_EMBEDDING_MODEL: text-embedding-3-large
