# Placeholder encrypted secrets file.
# Run `cp config/secrets/app.secrets.example.yaml config/secrets/app.secrets.yaml`
# followed by `sops --encrypt --in-place config/secrets/app.secrets.yaml`
# and rename the result to `app.secrets.enc.yaml` once you have real recipients.
