version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: newser
      POSTGRES_PASSWORD: newser
      POSTGRES_DB: newser
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
  app:
    build: .
    image: newser:latest
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: newser
      POSTGRES_PASSWORD: newser
      POSTGRES_DB: newser
      JWT_SECRET: dev-secret-change-me
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}
  redisdata: {}

 