services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: newser
      POSTGRES_PASSWORD: newser
      POSTGRES_DB: newser
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    image: newser:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NEWSER_STORAGE_POSTGRES_HOST: postgres
      NEWSER_STORAGE_POSTGRES_PORT: "5432"
      NEWSER_STORAGE_POSTGRES_USER: newser
      NEWSER_STORAGE_POSTGRES_PASSWORD: newser
      NEWSER_STORAGE_POSTGRES_DB: newser
      NEWSER_STORAGE_REDIS_HOST: redis
      NEWSER_STORAGE_REDIS_PORT: "6379"
    entrypoint: ["/usr/local/bin/newser"]
    command: ["migrate", "up"]
    restart: "no"
    volumes:
      - ./config:/app/config:ro

  api:
    image: newser:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      NEWSER_STORAGE_POSTGRES_HOST: postgres
      NEWSER_STORAGE_POSTGRES_PORT: "5432"
      NEWSER_STORAGE_POSTGRES_USER: newser
      NEWSER_STORAGE_POSTGRES_PASSWORD: newser
      NEWSER_STORAGE_POSTGRES_DB: newser
      NEWSER_STORAGE_REDIS_HOST: redis
      NEWSER_STORAGE_REDIS_PORT: "6379"
      CORS_ALLOW_ORIGINS: "http://localhost:3000"
      JWT_SECRET: dev-secret-change-me
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    entrypoint: ["/usr/local/bin/api"]
    command: ["--config", "/app/config/config.json"]
    ports:
      - "10001:10001"
    volumes:
      - ./config:/app/config:ro

  worker:
    image: newser:latest
    depends_on:
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      NEWSER_STORAGE_POSTGRES_HOST: postgres
      NEWSER_STORAGE_POSTGRES_PORT: "5432"
      NEWSER_STORAGE_POSTGRES_USER: newser
      NEWSER_STORAGE_POSTGRES_PASSWORD: newser
      NEWSER_STORAGE_POSTGRES_DB: newser
      NEWSER_STORAGE_REDIS_HOST: redis
      NEWSER_STORAGE_REDIS_PORT: "6379"
    entrypoint: ["/usr/local/bin/worker"]
    command: ["--config", "/app/config/config.json"]
    volumes:
      - ./config:/app/config:ro

  executor:
    image: newser:latest
    depends_on:
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      NEWSER_STORAGE_POSTGRES_HOST: postgres
      NEWSER_STORAGE_POSTGRES_PORT: "5432"
      NEWSER_STORAGE_POSTGRES_USER: newser
      NEWSER_STORAGE_POSTGRES_PASSWORD: newser
      NEWSER_STORAGE_POSTGRES_DB: newser
      NEWSER_STORAGE_REDIS_HOST: redis
      NEWSER_STORAGE_REDIS_PORT: "6379"
    entrypoint: ["/usr/local/bin/executor"]
    command: ["--config", "/app/config/config.json"]
    volumes:
      - ./config:/app/config:ro

  crawler:
    image: newser:latest
    depends_on:
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      NEWSER_STORAGE_POSTGRES_HOST: postgres
      NEWSER_STORAGE_POSTGRES_PORT: "5432"
      NEWSER_STORAGE_POSTGRES_USER: newser
      NEWSER_STORAGE_POSTGRES_PASSWORD: newser
      NEWSER_STORAGE_POSTGRES_DB: newser
      NEWSER_STORAGE_REDIS_HOST: redis
      NEWSER_STORAGE_REDIS_PORT: "6379"
    entrypoint: ["/usr/local/bin/crawler"]
    command: ["--config", "/app/config/config.json"]
    volumes:
      - ./config:/app/config:ro

  memory:
    image: newser:latest
    depends_on:
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      NEWSER_STORAGE_POSTGRES_HOST: postgres
      NEWSER_STORAGE_POSTGRES_PORT: "5432"
      NEWSER_STORAGE_POSTGRES_USER: newser
      NEWSER_STORAGE_POSTGRES_PASSWORD: newser
      NEWSER_STORAGE_POSTGRES_DB: newser
      NEWSER_STORAGE_REDIS_HOST: redis
      NEWSER_STORAGE_REDIS_PORT: "6379"
    entrypoint: ["/usr/local/bin/memory"]
    command: ["--config", "/app/config/config.json"]
    volumes:
      - ./config:/app/config:ro

  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:10001}
    image: newser-webui:latest
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata: {}
  redisdata: {}
