openapi: 3.0.3
info:
  title: Newser API
  version: 0.1.0
servers:
  - url: /api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /auth/signup:
    post:
      summary: Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '201': { description: Created }
  /auth/login:
    post:
      summary: Login
      description: Returns JWT in cookie and body; supports Bearer tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: OK (sets auth cookie and returns token)
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }
  /topics:
    security:
      - bearerAuth: []
      - cookieAuth: []
    get:
      summary: List topics
      responses: { '200': { description: OK } }
    post:
      summary: Create topic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                preferences: { type: object }
                schedule_cron: { type: string }
      responses:
        '201': { description: Created }
  /topics/{topic_id}/runs:
    security:
      - bearerAuth: []
      - cookieAuth: []
    get:
      summary: List runs of a topic
      parameters:
        - in: path
          name: topic_id
          required: true
          schema: { type: string }
      responses: { '200': { description: OK } }
  /topics/{topic_id}/trigger:
    security:
      - bearerAuth: []
      - cookieAuth: []
    post:
      summary: Trigger a run for a topic
      parameters:
        - in: path
          name: topic_id
          required: true
          schema: { type: string }
      responses:
        '202': { description: Accepted }
  /topics/{topic_id}/latest_result:
    security:
      - bearerAuth: []
      - cookieAuth: []
    get:
      summary: Get latest processing result for a topic
      description: Requires authentication via cookie or Bearer token.
      parameters:
        - in: path
          name: topic_id
          required: true
          schema: { type: string }
      responses: { '200': { description: OK }, '404': { description: Not found } }


